language = "en"
territory = "xx"
modifier = "blank"

[messages]


found-matching = "Found ($matches) package(s) matching: ($search)\n"
none-matching = "No packages found matching ($search)!"
install-select = "Selecting ($package) from ($manager) for installation."
remove-select = "Selecting ($package) from ($manager) for removal."


[message.invalid]
number = "($number) is not a valid number!"
repository = "($repo) is not a valid repository!"

[message.ask]
sure =      "Are you sure?"
which-install =   "Select which package(s) to install [0-($index)]:"
which-remove =    "Select which package(s) to remove [0-($index)]:"
upgrade = "Are you sure you want to upgrade all packages?"
[messages.searching]
apt =       "Searching apt…"
pacstall =  "Searching pacstall…"
snap =      "Searching snap…"
flatpak =   "Searching flatpak…"

